sources:
  - name: public
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: public
    tables:
      - name: marcas
        description: "Table containing brand information"
      - name: embalagens
        description: "Table containing packaging information"
      - name: empresas
        description: "Table containing company information"
      - name: pontos_de_venda
        description: "Table containing customers information (some information only)"
      - name: coletas_09_25
        description: "Table containing research collections data from September 2025"
      - name: coletas_12_25
        description: "Table containing research collections data from December 2025"

models:
  - name: stg_marcas
    description: "Staging table for brands"
    columns:
      - name: cod_marca
        description: "Brand code"
      - name: desc_marca
        description: "Brand description"
      - name: seg_preco
        description: "Brand price segment"
      - name: desc_fabricante
        description: "Brand manufacturer description"
  
  - name: stg_empresas

  - name: stg_embalagens
    description: "Staging table for packaging"
    columns:
      - name: cod_embalagem
        description: "Packaging code"
      - name: desc_embalagem
        description: "Packaging description"
      - name: qtd_unidades
        description: "Quantity of units in the packaging"
      - name: qtd_litros
        description: "Total amount of liters of the packaging (considering all units in the packaging)"

  - name: stg_pontos_de_venda
  - name: stg_coletas_set_25
  - name: stg_coletas_dez_25