version: 2

models:
  - name: stg_marcas
    description: "Tabela de preparação para marcas"
    columns:
      - name: cod_marca
        description: "Código da marca"
      - name: desc_marca
        description: "Descrição da marca"
      - name: seg_preco
        description: "Segmento de preço da marca"
      - name: desc_fabricante
        description: "Descrição do fabricante"

  - name: stg_empresas
    description: "Tabela de preparação para empresas"
    columns:
      - name: cod_empresa
        description: "Código da empresa"
      - name: desc_empresa
        description: "Descrição da empresa"
      - name: continente
        description: "Continente da empresa"

  - name: stg_embalagens
    description: "Tabela de preparação para embalagens"
    columns:
      - name: cod_embalagem
        description: "Código da embalagem"
      - name: desc_embalagem
        description: "Descrição da embalagem"
      - name: qtd_unidades
        description: "Quantidade de unidades na embalagem"
      - name: vol_litros
        description: "Volume total em litros da embalagem (considerando todas as unidades na embalagem)"

  - name: stg_pontos_de_venda
    description: "Tabela de preparação para pontos de venda"
    columns:
      - name: cod_empresa
        description: "Código da empresa à qual o cliente pertence"
        tests:
          - not_null:
              arguments: {}
              severity: error
      - name: cod_cliente
        description: "Código do cliente"
        tests:
          - not_null:
              arguments: {}
              severity: error
      - name: canal
        description: "Canal de venda do cliente"
        tests:
          - accepted_values:
              values: ['Bares', 'Bares VIP', 'Mercados', 'Subdistribuidor']
              severity: warn
      - name: cidade
        description: "Cidade onde o cliente está localizado"

  - name: stg_date
    description: "Tabela calendário"
    columns:
      - name: date_day 
        description: "Data do dia"
      - name: prior_date_day 
        description: "Data do dia anterior"
      - name: next_date_day
        description: "Data do dia seguinte"
      - name: prior_year_date_day 
        description: "Mesmo dia do ano anterior"
      - name: prior_year_over_year_date_day 
        description: "Descrever..."
      - name: day_of_week 
        description: "Dia da semana em número"
      - name: day_of_week_name 
        description: "Nome do dia da semana"
      - name: day_of_week_name_short
        description: "Nome curto do dia da semana"
      - name: day_of_month
        description: "Dia do mês"
      - name: day_of_year
        description: "Dia do ano"
      - name: week_start_date
        description: "Data do início da semana"
      - name: week_end_date
        description: "Data do fim da semana"
      - name: prior_year_week_start_date
        description: "Descrever..."
      - name: prior_year_week_end_date
        description: "Descrever..."
      - name: week_of_year
        description: "Descrever..."
      - name: iso_week_start_date
        description: "Descrever..."
      - name: iso_week_end_date
        description: "Descrever..."
      - name: prior_year_iso_week_start_date
        description: "Descrever..."
      - name: prior_year_iso_week_end_date 
        description: "Descrever..."
      - name: iso_week_of_year 
        description: "Descrever..."
      - name: prior_year_week_of_year 
        description: "Descrever..."
      - name: prior_year_iso_week_of_year 
        description: "Descrever..."
      - name: month_of_year 
        description: "Descrever..."
      - name: month_name
        description: "Descrever..."
      - name: month_name_short
        description: "Descrever..."
      - name: month_start_date
        description: "Descrever..."
      - name: month_end_date
        description: "Descrever..."
      - name: prior_year_month_start_date
        description: "Descrever..."
      - name: prior_year_month_end_date
        description: "Descrever..."
      - name: quarter_of_year
        description: "Descrever..."
      - name: quarter_start_date
        description: "Descrever..."
      - name: quarter_end_date
        description: "Descrever..."
      - name: year_number
        description: "Descrever..."
      - name: year_start_date
        description: "Descrever..."
      - name: year_end_date

  - name: stg_coletas_set_25
    description: "Tabela de preparação para coletas de setembro de 2025"
    columns:
      - name: cod_empresa
        description: "Código da empresa à qual o cliente pertence"
      - name: cod_cliente
        description: "Código do cliente"
      - name: cod_embalagem
        description: "Código da embalagem do produto coletado"
      - name: cod_marca
        description: "Código da marca do produto coletado"
      - name: vol_cxs
        description: "Volume coletado em caixas"
      - name: pv
        description: "Preço de compra do produto pelo ponto de venda em pacote"
      - name: pp
        description: "Preço pago pelo cliente por unidade (não pacote) de um produto"
      - name: mes_coletas
        description: "Mês de coleta da pesquisa"

  - name: stg_coletas_dez_25
    description: "Tabela de preparação para coletas de dezembro de 2025"
    columns:
      - name: cod_empresa
        description: "Código da empresa à qual o cliente pertence"
      - name: cod_cliente
        description: "Código do cliente"
      - name: cod_embalagem
        description: "Código da embalagem do produto coletado"
      - name: cod_marca
        description: "Código da marca do produto coletado"
      - name: vol_cxs
        description: "Volume coletado em caixas"
      - name: pv
        description: "Preço de compra do produto pelo ponto de venda em pacote"
      - name: pp
        description: "Preço pago pelo cliente por unidade (não pacote) de um produto"
      - name: mes_coletas
        description: "Mês de coleta da pesquisa"