version: 2

models:
  - name: mart_fct_coletas
    description: "Tabela de coletas consolidada"
    columns:
      - name: cod_empresa 
        description: "Código da empresa à qual o cliente pertence"
        tests:
          - relationships:
              to: ref('mart_dim_empresas')
              field: cod_empresa
              severity: error
      - name: cod_emp_pdv
        description: "Código da empresa e do ponto de venda concatenados"
        tests:
          - relationships:
              to: ref('mart_dim_pdvs')
              field: cod_emp_pdv
              severity: error
      - name: cod_embalagem
        description: "Código da embalagem do produto coletado"
        tests:
          - relationships:
              to: ref('mart_dim_embalagens')
              field: cod_embalagem
              severity: error
      - name: cod_marca
        description: "Código da marca do produto coletado"
        tests:
          - relationships:
              to: ref('mart_dim_marcas')
              field: cod_marca
      - name: vol_cxs
        description: "Volume coletado em caixas"
      - name: vol_hl
        description: "Volume coletado em hectolitros"
      - name: pv
        description: "Preço de compra do produto pelo ponto de venda em caixas"
      - name: pp
        description: "Preço pago pelo cliente por unidade (não pacote) de um produto"
      - name: mes_coletas
        description: "Mês de coleta da pesquisa"
        tests:
          - relationships:
              to: ref('mart_dim_date')
              field: date_day
              severity: error